### ISSUE TITLE
ArrayIndexOutOfBoundsException on Anroid run on playing a mp3 file

### ISSUE THREAD

**Issue by TobseF** [korlibs/korau#18]
After Upgrading from Korge `1.10.0.0` to `1.12.2.0` the 
`VfsFile.readSound()` doesn't work anymore for a specific mp3 file. 
Platform: `installAndroidDebug`

You can find the Sound files here:
https://github.com/TobseF/HitKlack/tree/master/src/commonMain/resources/sounds
The file which causes the exception is the `line_missed.mp3`. 
The other Sounds work. - Sometimes a bit choppy but OK.
The full project:
https://github.com/TobseF/HitKlack/tree/UpgradeKorge

**ArrayIndexOutOfBoundsException**
![2020-04-28_01h09_23](https://user-images.githubusercontent.com/1190109/80430094-f0650380-88ed-11ea-9269-198bcfef2542.png)

**Comment by soywiz** [comment]
Strangely I added that same file here: https://github.com/korlibs/korau/blob/ff8cba902416e596eca16f86843734b880916edb/korau/src/commonTest/kotlin/com/soywiz/korau/format/mp3/SoftMp3DecoderTest.kt#L22
And tests are passing and was failing because of the ID3v2 at the beginning. I will investigate further.

**Comment by soywiz** [comment]
Still the MP3 library I ported to Kotlin caused lot of troubles and the quality seems to not be pretty good. But the automatic minimp3 conversion I did using ktcc caused problems with Kotlin/Native. So maybe what I should do is to port minimp3 manually to plain kotlin.

**Comment by TobseF** [comment]
I checked the new version. Exception is fixed 👍 
But you are right. The sounds is choppy and about one of four times it's even muted (the same sound file).

**Comment by soywiz** [comment]
Fixed here, hopefully finally for the good. I have added tests to avoid regressions: https://github.com/korlibs/korge/pull/503
