### ISSUE TITLE
Restore minimp3 implementation for all the targets

### ISSUE THREAD

**Issue by soywiz** [korlibs/korau#22]
Tried to port a pure-java library for MP3, but the quality of the library seems to not be too good and relied on `ArrayIndexOutOfBoundsException` and have some output issues. So let's try to restore minimp3 again. Maybe we convert it to pure Kotlin later (without the HEAP and the inline classes, step by step)

Tries to handle issues commented here: #18

**Comment by RezMike** [comment]
What steps do we need to take to implement it? Maybe I can help somewhere here.

**Comment by RezMike** [comment]
If all we need here is to convert "dirty" kotlin code after ktcc conversion to pure kotlin code, I can do that

**Comment by soywiz** [comment]
I wanted to support the minimp3_ex.h here: https://github.com/lieff/minimp3/blob/master/minimp3_ex.h
to support seeking and stuff. But ktcc https://github.com/korlibs/ktcc produce some errors that might require some work. So probably some work needed on ktcc. Do you want to try to fix ktcc issues? It is a C compiler that generates kotlin

**Comment by RezMike** [comment]
Well, I can take a look in a while and maybe do something.

**Comment by soywiz** [comment]
Superseded by https://github.com/korlibs/korlibs-audio/issues/3
