### ISSUE TITLE
Music jittering, speeding up, and echoing on Windows JVM 

### ISSUE THREAD

**Issue by Clintonio** [korlibs/korau#33]
Platform: Windows 10 JVM 17
Reproducibility: 100%
Repo that reproduces the issue: https://github.com/Clintonio/korau-bug-example

Description:

Whenever running the (GUIless) code in the above repository, which runs one piece of music, and then the same sound 100 times, the music will become faster, jitterier, and echoier the more often the other sound is played.

I do not have a video to demonstrate this as I am running Korau in this repository without a GUI and recording just sound from an application is not something I have familiarity with (OBS, perhaps?), but you can clone the repository and run it in under a minute. 

I have tried this on one other _Windows 10_ machine and the issue persists. I have not tested other configurations as I am only targeting this platform at this time.

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge/pull/503

**Comment by Clintonio** [comment]
Amazing, thanks for the fast implementation.
