### ISSUE TITLE
Support loop playing

### ISSUE THREAD

**Issue by soywiz** [korlibs/korau#4]

**Comment by soywiz** [comment]
[src__music_loop_.zip](https://github.com/korlibs/korau/files/4115503/src__music_loop_.zip)

**Comment by SerVB** [comment]
Story is here: https://soywiz.slack.com/archives/CH2RW1UH5/p1579771261006700

>  Just change `src` dir of `korge-hello-world` to this one.

> I've just added lines of music playing to the `main` and added a music file to `resources`.

**Comment by SerVB** [comment]
It seems that a browser just hangs after the first iteration of the music. In JVM, it works fine.

**Comment by soywiz** [comment]
Implemented on master on the JVM. Need to clean things up and ensure it is working on other targets.
